import dotenv from 'dotenv';
import { scrapeTrending } from './scraper.js';
import { generateCarouselContent } from './generator.js';
import { renderCarouselPngs } from './renderer.js';

dotenv.config();

async function main() {
  console.log('=== Starting AI/Tech Carousel Generator Pipeline (CLI Mode) ===');
  
  try {
    // Determine timeslot based on arguments, defaulting to am/pm based on hour
    let timeSlot = null;
    const args = process.argv.slice(2);
    if (args.length > 0 && (args[0] === 'am' || args[0] === 'pm')) {
      timeSlot = args[0];
      console.log(`Running manually for time slot: ${timeSlot.toUpperCase()}`);
    }

    // 1. Scrape trending stories
    const topStories = await scrapeTrending(timeSlot);
    
    if (topStories.length === 0) {
      console.error('No trending stories found. Exiting.');
      return;
    }
    
    // 2. Select story (default to first/top, or select by command-line argument if a number is passed)
    let selectedIndex = 0;
    const numberArg = args.find(arg => !isNaN(parseInt(arg, 10)));
    if (numberArg) {
      const argIndex = parseInt(numberArg, 10);
      if (argIndex >= 1 && argIndex <= topStories.length) {
        selectedIndex = argIndex - 1;
        console.log(`Selecting story index: ${argIndex}`);
      }
    }
    
    const selectedStory = topStories[selectedIndex];
    console.log(`Selected Story: [${selectedStory.sources.join(', ')}] ${selectedStory.title}`);
    
    // 3. Generate slide content via Gemini AI
    let slidesData;
    if (!process.env.GEMINI_API_KEY && !process.env.NVIDIA_API_KEY) {
      console.log('No GEMINI_API_KEY or NVIDIA_API_KEY detected. Using mockup slides content for local rendering test...');
      slidesData = {
        date: new Date().toISOString().split('T')[0],
        linkedin_post: "This is a mock LinkedIn post caption that would normally be generated by the NVIDIA NIM LLM. It includes a hook, key points, and hashtags.\n\n#AI #TechNews #Testing",
        slides: [
          {
            slide_number: 1,
            type: "intro",
            headline: "Mock Headline: AI Redesign",
            subheadline: "This is a placeholder subheadline demonstrating local PNG screenshot rendering."
          },
          {
            slide_number: 2,
            type: "story",
            title: "The Visual Redesign",
            content: "We successfully migrated the layout to match the approved reference Canva templates. Headings now use Bebas Neue, backgrounds have repeating diagonal lines, and themes alternate."
          },
          {
            slide_number: 3,
            type: "deep_dive",
            title: "Under The Hood",
            content: "The rendering uses a headless browser at double pixel density for crisp rendering. The CSS variables map directly to custom colors configured in your environment."
          },
          {
            slide_number: 4,
            type: "impact",
            title: "Value Proposition",
            content: "No persistent disk or paid storage is required. Render runs the stateless Puppeteer container, and Supabase manages the JSON logs and PNG asset hosting for free."
          },
          {
            slide_number: 5,
            type: "outro",
            headline: "THANK YOU!",
            subheadline: "Follow for daily AI & tech breakdowns. Share your thoughts in the comments!"
          }
        ]
      };
    } else {
      slidesData = await generateCarouselContent(selectedStory, timeSlot || 'am');
    }
    
    // Log the generated content for debugging
    console.log('Slide Structure:');
    console.log(JSON.stringify(slidesData, null, 2));
    
    // 4. Render to PNGs
    const renderResult = await renderCarouselPngs(slidesData);
    
    console.log('----------------------------------------------------');
    console.log('Local PNGs generated successfully!');
    console.log(`Run ID: ${renderResult.runId}`);
    console.log(`Directory: ${renderResult.runDir}`);
    console.log('Generated Files:');
    renderResult.imagePaths.forEach(p => console.log(` - ${p}`));
    console.log('----------------------------------------------------');
    
  } catch (error) {
    console.error('Error running the pipeline:', error);
    process.exit(1);
  }
}

main();
